### ISSUE TITLE
Crashed on R27 dxf import: NullPointerException

### ISSUE THREAD

**Issue by simon04** [JOSM/Dxf-Import#2]
From https://josm.openstreetmap.de/ticket/12403:

```
URL:http://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2016-01-06 17:30:31 +0100 (Wed, 06 Jan 2016)
Build-Date:2016-01-06 16:32:31
Revision:9329
Relative:URL: ^/trunk

Identification: JOSM/1.5 (9329 de) Linux Ubuntu 14.04.3 LTS
Memory Usage: 779 MB / 1762 MB (272 MB allocated, but free)
Java version: 1.8.0_66, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
VM arguments: [-Djava.security.policy=file:/usr/lib/jvm/java-8-oracle/jre/lib/security/javaws.policy, -DtrustProxy=true, -Djnlpx.home=<java.home>/bin, -Djava.security.manager, -Djnlpx.origFilenameArg=/tmp/mozilla_marc0/josm-1.jnlp, -Djnlpx.remove=false, -Dsun.awt.warmup=true, -Djava.util.Arrays.useLegacyMergeSort=true, -Djnlpx.splashport=42185, -Djnlpx.jvm=<java.home>/bin/java, -Djnlpx.vmargs=LURqYXZhLnV0aWwuQXJyYXlzLnVzZUxlZ2FjeU1lcmdlU29ydD10cnVlAA==]
Dataset consistency test: No problems found

Plugins:
- BuildingGeneralization (UNKNOWN)
- ColorPlugin (1414145445)
- DirectDownload (31934)
- DxfImport (1006)
- FixAddresses (31772)
- HouseNumberTaggingTool (31772)
- buildings_tools (31895)
- cadastre-fr (31772)
- ejml (31895)
- fieldpapers (v0.4.0)
- geotools (31895)
- jts (31772)
- namemanager (31772)
- terracer (31895)

Last errors/warnings:
- E: java.io.IOException: java.lang.NullPointerException. Ursache: java.lang.NullPointerException
- E: java.io.IOException: java.lang.NullPointerException. Ursache: java.lang.NullPointerException

java.io.IOException: java.lang.NullPointerException
    at org.openstreetmap.josm.plugins.dxfimport.DxfImportTask.realRun(DxfImportTask.java:191)
    at org.openstreetmap.josm.gui.PleaseWaitRunnable.doRealRun(PleaseWaitRunnable.java:93)
    at org.openstreetmap.josm.gui.PleaseWaitRunnable.run(PleaseWaitRunnable.java:161)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at org.openstreetmap.josm.plugins.dxfimport.DxfImportTask.realRun(DxfImportTask.java:178)
    ... 7 more
```

**Comment by don-vip** [comment]
Should be fixed in https://github.com/JOSM/Dxf-Import/releases/tag/v1012
