### ISSUE TITLE
Fails to open DXF file

### ISSUE THREAD

**Issue by naoliv** [JOSM/Dxf-Import#3]
While trying to open [this nice DXF file](http://naoliv.iq.unesp.br/osm/nice.dxf) the plugin fails with:

```
mar 31, 2016 11:40:16 AM com.kitfox.svg.xml.StyleAttribute getURIValue
ADVERTÊNCIA: null
java.net.URISyntaxException: Illegal character in fragment at index 3: #A_#36_C3A5D47D2
    at java.net.URI$Parser.fail(URI.java:2848)
    at java.net.URI$Parser.checkChars(URI.java:3021)
    at java.net.URI$Parser.parse(URI.java:3067)
    at java.net.URI.<init>(URI.java:588)
    at com.kitfox.svg.xml.StyleAttribute.getURIValue(StyleAttribute.java:268)
    at com.kitfox.svg.Use.updateTime(Use.java:227)
    at com.kitfox.svg.Group.updateTime(Group.java:315)
    at com.kitfox.svg.Group.updateTime(Group.java:315)
    at com.kitfox.svg.Group.updateTime(Group.java:315)
    at com.kitfox.svg.SVGRoot.updateTime(SVGRoot.java:354)
    at com.kitfox.svg.SVGDiagram.updateTime(SVGDiagram.java:230)
    at com.kitfox.svg.SVGUniverse.loadSVG(SVGUniverse.java:611)
    at com.kitfox.svg.SVGUniverse.loadSVG(SVGUniverse.java:465)
    at com.kitfox.svg.SVGUniverse.getDiagram(SVGUniverse.java:400)
    at com.kitfox.svg.SVGUniverse.getDiagram(SVGUniverse.java:364)
    at org.openstreetmap.josm.plugins.dxfimport.DxfImportTask.realRun(DxfImportTask.java:175)
    at org.openstreetmap.josm.gui.PleaseWaitRunnable.doRealRun(PleaseWaitRunnable.java:93)
    at org.openstreetmap.josm.gui.PleaseWaitRunnable.run(PleaseWaitRunnable.java:161)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

mar 31, 2016 11:40:16 AM com.kitfox.svg.SVGUniverse loadSVG
ADVERTÊNCIA: Could not load SVG file:/tmp/importTaskTemp7277405412270312212.dxf
java.lang.NullPointerException
    at com.kitfox.svg.Use.updateTime(Use.java:229)
    at com.kitfox.svg.Group.updateTime(Group.java:315)
    at com.kitfox.svg.Group.updateTime(Group.java:315)
    at com.kitfox.svg.Group.updateTime(Group.java:315)
    at com.kitfox.svg.SVGRoot.updateTime(SVGRoot.java:354)
    at com.kitfox.svg.SVGDiagram.updateTime(SVGDiagram.java:230)
    at com.kitfox.svg.SVGUniverse.loadSVG(SVGUniverse.java:611)
    at com.kitfox.svg.SVGUniverse.loadSVG(SVGUniverse.java:465)
    at com.kitfox.svg.SVGUniverse.getDiagram(SVGUniverse.java:400)
    at com.kitfox.svg.SVGUniverse.getDiagram(SVGUniverse.java:364)
    at org.openstreetmap.josm.plugins.dxfimport.DxfImportTask.realRun(DxfImportTask.java:175)
    at org.openstreetmap.josm.gui.PleaseWaitRunnable.doRealRun(PleaseWaitRunnable.java:93)
    at org.openstreetmap.josm.gui.PleaseWaitRunnable.run(PleaseWaitRunnable.java:161)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

diagram: 
com.kitfox.svg.SVGDiagram@6d59a34e
root: 
com.kitfox.svg.SVGRoot@53ddf9a9
mar 31, 2016 11:40:16 AM com.kitfox.svg.SVGUniverse getElement
ADVERTÊNCIA: Could not parse path null
java.lang.NullPointerException
    at com.kitfox.svg.SVGUniverse.getElement(SVGUniverse.java:335)
    at com.kitfox.svg.SVGUniverse.getElement(SVGUniverse.java:307)
    at com.kitfox.svg.Use.getBoundingBox(Use.java:152)
    at com.kitfox.svg.Group.calcBoundingBox(Group.java:274)
    at com.kitfox.svg.Group.getBoundingBox(Group.java:252)
    at com.kitfox.svg.Group.calcBoundingBox(Group.java:274)
    at com.kitfox.svg.Group.getBoundingBox(Group.java:252)
    at com.kitfox.svg.Group.calcBoundingBox(Group.java:274)
    at com.kitfox.svg.Group.getBoundingBox(Group.java:252)
    at com.kitfox.svg.SVGRoot.getBoundingBox(SVGRoot.java:326)
    at org.openstreetmap.josm.plugins.dxfimport.DxfImportTask.realRun(DxfImportTask.java:183)
    at org.openstreetmap.josm.gui.PleaseWaitRunnable.doRealRun(PleaseWaitRunnable.java:93)
    at org.openstreetmap.josm.gui.PleaseWaitRunnable.run(PleaseWaitRunnable.java:161)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
(...)
ERRO: java.io.IOException: java.lang.NullPointerException. Causa: java.lang.NullPointerException
java.io.IOException: java.lang.NullPointerException
    at org.openstreetmap.josm.plugins.dxfimport.DxfImportTask.realRun(DxfImportTask.java:191)
    at org.openstreetmap.josm.gui.PleaseWaitRunnable.doRealRun(PleaseWaitRunnable.java:93)
    at org.openstreetmap.josm.gui.PleaseWaitRunnable.run(PleaseWaitRunnable.java:161)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at com.kitfox.svg.Path.getBoundingBox(Path.java:103)
    at com.kitfox.svg.Group.calcBoundingBox(Group.java:274)
    at com.kitfox.svg.Group.getBoundingBox(Group.java:252)
    at com.kitfox.svg.Group.calcBoundingBox(Group.java:274)
    at com.kitfox.svg.Group.getBoundingBox(Group.java:252)
    at com.kitfox.svg.Group.calcBoundingBox(Group.java:274)
    at com.kitfox.svg.Group.getBoundingBox(Group.java:252)
    at com.kitfox.svg.SVGRoot.getBoundingBox(SVGRoot.java:326)
    at org.openstreetmap.josm.plugins.dxfimport.DxfImportTask.realRun(DxfImportTask.java:183)
    ... 7 more
ERRO: java.io.IOException: java.lang.NullPointerException. Causa: java.lang.NullPointerException
java.io.IOException: java.lang.NullPointerException
    at org.openstreetmap.josm.plugins.dxfimport.DxfImportTask.realRun(DxfImportTask.java:191)
    at org.openstreetmap.josm.gui.PleaseWaitRunnable.doRealRun(PleaseWaitRunnable.java:93)
    at org.openstreetmap.josm.gui.PleaseWaitRunnable.run(PleaseWaitRunnable.java:161)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at com.kitfox.svg.Path.getBoundingBox(Path.java:103)
    at com.kitfox.svg.Group.calcBoundingBox(Group.java:274)
    at com.kitfox.svg.Group.getBoundingBox(Group.java:252)
    at com.kitfox.svg.Group.calcBoundingBox(Group.java:274)
    at com.kitfox.svg.Group.getBoundingBox(Group.java:252)
    at com.kitfox.svg.Group.calcBoundingBox(Group.java:274)
    at com.kitfox.svg.Group.getBoundingBox(Group.java:252)
    at com.kitfox.svg.SVGRoot.getBoundingBox(SVGRoot.java:326)
    at org.openstreetmap.josm.plugins.dxfimport.DxfImportTask.realRun(DxfImportTask.java:183)
    ... 7 more
```

JOSM version is 10089

**Comment by don-vip** [comment]
Can you please test with ​https://github.com/JOSM/Dxf-Import/releases/tag/v1012 ?

**Comment by naoliv** [comment]
While it seems to be a slow and memory hungry process, now it works :-)
Thanks!
