### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by naoliv** [JOSM/Dxf-Import#5]
Today with the latest JOSM (version 10436) I am seeing this:

```
INFO: loading plugin 'DxfImport' (version 1006)
ERROR: org.openstreetmap.josm.plugins.PluginException: An error occurred in plugin DxfImport. Cause: java.lang.reflect.InvocationTargetException. Cause: java.lang.IllegalAccessError: tried to access field org.openstreetmap.josm.actions.ExtensionFileFilter.importers from class org.openstreetmap.josm.plugins.dxfimport.DxfImportPlugin
org.openstreetmap.josm.plugins.PluginException: An error occurred in plugin DxfImport
    at org.openstreetmap.josm.plugins.PluginInformation.load(PluginInformation.java:329)
    at org.openstreetmap.josm.plugins.PluginHandler.loadPlugin(PluginHandler.java:715)
    at org.openstreetmap.josm.plugins.PluginHandler.loadPlugins(PluginHandler.java:777)
    at org.openstreetmap.josm.plugins.PluginHandler.loadLatePlugins(PluginHandler.java:816)
    at org.openstreetmap.josm.gui.MainApplication.loadLatePlugins(MainApplication.java:550)
    at org.openstreetmap.josm.gui.MainApplication.main(MainApplication.java:480)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.openstreetmap.josm.plugins.PluginInformation.load(PluginInformation.java:326)
    ... 5 more
Caused by: java.lang.IllegalAccessError: tried to access field org.openstreetmap.josm.actions.ExtensionFileFilter.importers from class org.openstreetmap.josm.plugins.dxfimport.DxfImportPlugin
    at org.openstreetmap.josm.plugins.dxfimport.DxfImportPlugin.<init>(DxfImportPlugin.java:12)
    ... 10 more
WARNING: Disable plugin - Could not load plugin DxfImport. Delete from preferences?
```

**Comment by don-vip** [comment]
The plugin needs update, we have duplicate reports: https://josm.openstreetmap.de/ticket/13213

**Comment by don-vip** [comment]
I already provided the PR (https://github.com/asrianCron/Dxf-Import/pull/4) can you make a new release?

**Comment by mikelortega** [comment]
Do you have any update on this? In my case I don't get any error, but when I try to open a dxf file it just does nothing. Tell me if there is a way to give you more info about it. Thank you.

**Comment by don-vip** [comment]
Can you please share your file somewhere?

**Comment by mikelortega** [comment]
I'm trying with this file [http://b5m.gipuzkoa.eus/dxfs/PTII-c.zip](http://b5m.gipuzkoa.eus/dxfs/PTII-c.zip) but it's the same with any other. I guess I'm just doing something wrong.

**Comment by don-vip** [comment]
Fixed in v1010

**Comment by ltr-afk** [comment]
Hi, I have the same issue. When I try to open a dxf file, it does nothing. There is no error. The plugin version is 1013.
